cds-rfp:
    enable-grpc-security: false
    security:
        host: 192.168.63.14
        port: 33861
    grpc:
        port: 8030
    datasource:
        host: 192.168.63.15
        port: 15432
        name: sampledb
        username: userUD6
        password: fXrgrCUiw7rXOXLe
    yandex:
        api-key: keykey
        url: https://courier.common.yandex.ru/vrs/api/v1
        courier:
            clientId: 558
            url: https://courier.common.yandex.ru/api/v1/companies/${cds-rfp.yandex.courier.clientId}
            applId: bb36b83f2b64419a8e2c5d57fcb0b5e7
            token: AQAAAAAzh1PTAAWci0cpIWNTRkpSmroSNGNnyLA

hibernate:
    temp:
        use_jdbc_metadata_defaults: false
        
server:
    port: 8081
    servlet:
        context-path: /cds-rfp
        
spring:
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${cds-rfp.datasource.host}:${cds-rfp.datasource.port}/${cds-rfp.datasource.name}
        name:
        username: ${cds-rfp.datasource.username}
        password: ${cds-rfp.datasource.password}
        hikari:
              idle-timeout: 90000
    jpa:
        open-in-view: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.use_sql_comments: true
            hibernate.temp.use_jdbc_metadata_defaults: false        